default: &default
  iat_expiration_minutes: <%= ENV.fetch("IAT_EXPIRATION_MINUTES", 60).to_i %>
  create_election:
    hours_before: <%= ENV.fetch("HOURS_BEFORE_CREATE_ELECTION", 1).to_i %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
