version: "3.3"
services:
  bulletin:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    environment:
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
      - RACK_ENV=production
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    environment:
      - RAILS_LOG_TO_STDOUT=1
      - RACK_ENV=production
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379
    command: ""
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  redis_data: