inherit_from: https://raw.githubusercontent.com/decidim/decidim/develop/.rubocop_ruby.yml

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
