# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in decidim-bulletin_board-dummy.gemspec
gemspec

gem "rubocop", "~> 1.28.0"
gem "rubocop-faker", "~> 1.1.0"
gem "rubocop-rspec", "~> 2.10"
