# frozen_string_literal: true

require "active_model"
require "active_support/configurable"
require "decidim/bulletin_board/version"
require "jwt"
require "graphlient"
require "wisper"

require "decidim/bulletin_board/client"
require "decidim/bulletin_board/file_client"
require "decidim/bulletin_board/engine"
require "decidim/bulletin_board/jwk_utils"
require "decidim/bulletin_board/message_identifier"

module Decidim
  # This module holds all the logic for the Bulletin Board Ruby Client to connect
  # a Decidim instance with a Bulletin Board server
  module BulletinBoard
    include ActiveSupport::Configurable

    # Configure the following variables inside your
    # decidim_bulletin_board.rb initializer

    # The Bulletin Board server (String)
    config_accessor :bulletin_board_server

    # The public key (JSON) of the Bulletin Board server
    config_accessor :bulletin_board_public_key

    # The api key generated by the Bulletin Board for the Decidim authority (String)
    config_accessor :authority_api_key

    # The authority name (String)
    config_accessor :authority_name

    # The identification private key (JSON) for your Decidim instance
    config_accessor :authority_private_key

    # The voting scheme name
    config_accessor :scheme_name

    # The number of trustees for an election (Int). Must be higher than the quorum
    config_accessor :number_of_trustees

    # The quorum needed to start the tally
    config_accessor :quorum
  end
end
