package:
  name: electionguard
  version: 1.1.16
source:
  url: file:dist/electionguard-1.1.16.tar.gz
  patches:
    - patches/no-cryptography.patch
    - patches/no-multiprocessing.patch
requirements:
  run:
    - hypothesis
    - jsons
    - rsa
    - gmpy2
    - pyasn1
