package:
  name: electionguard
  version: 1.2.3
source:
  url: file:dist/electionguard-1.2.3.tar.gz
  patches:
    - patches/no-cryptography.patch
    - patches/no-multiprocessing.patch
requirements:
  run:
    - hypothesis
    - jsons
    - rsa
    - gmpy2
    - pyasn1
  test:
  imports:
    - electionguard
