package:
  name: gmpy2
  version: 2.0.8
source:
  sha256: dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f
  url: https://files.pythonhosted.org/packages/90/f4/9a2e384b325b69bc5827b9a6510a8fb4a51698c915c06a3f25a86458892a/gmpy2-2.0.8.zip
  patches:
    - patches/disable_mpc_mpfr.patch
build:
  skip_host: False
  ldflags: |
    -L../../../libgmp/gmp-6.2.1/.libs
  cflags: |
    -I../../../libgmp/gmp-6.2.1
test:
  imports:
  - gmpy2
requirements:
  run:
    - libgmp