# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in decidim-bulletin_board.gemspec
gemspec

gem "rspec-rails", "~> 3.7"
gem "rubocop", "~> 0.92.0"
gem "rubocop-faker"
gem "rubocop-rspec", "~> 1.21"
