query GetElectionLogEntries($electionUniqueId: String!, $after: String) {
  election(uniqueId: $electionUniqueId) {
    logEntries(after: $after) {
      id
      messageId
      signedData
    }
  }
}
