query GetElectionLogEntries($electionUniqueId: String!, $contentHash: String!) {
  logEntry(electionUniqueId: $electionUniqueId, contentHash: $contentHash) {
    logEntry {
      messageId
      signedData
      contentHash
    }
  }
}
