inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/develop/decidim-dev/config/rubocop/ruby.yml
  - https://raw.githubusercontent.com/decidim/decidim/develop/decidim-dev/config/rubocop/rspec.yml
  - https://raw.githubusercontent.com/decidim/decidim/develop/decidim-dev/config/rubocop/rails.yml

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "node_modules/**/*"
    - "db/schema.rb"
    - "vendor/**/*"

Style/OpenStructUse:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false