# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby RUBY_VERSION

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 6.1.7"
# Use postgresql as the database for Active Record
gem "pg", ">= 0.18", "< 2.0"
# Use GraphQL for the API communication
gem "graphql", "~> 1.12.24"
gem "graphql-guard", "~> 2.0"
# Use Puma as the app server
gem "puma", "~> 5.3"
gem "redcarpet"
# Use SCSS for stylesheets
gem "sass-rails", ">= 6"
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem "webpacker", "~> 6.0.0.pre.2"
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.7"
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'
gem "jsonl"
gem "pycall"
gem "redis", "~> 4.0"
gem "zlib"

# just in case anyone uses S3
gem "aws-sdk-s3", require: false
# uncomment if using these alternatives
# gem "azure-storage-blob", "~> 2.0", require: false
# gem "google-cloud-storage", "~> 1.11", require: false

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false
gem "faker", "~> 2.14"
gem "graphiql-rails"
gem "jquery-rails"
gem "jwt"
gem "rack-cors"
gem "rectify", "~> 0.13.0"
gem "sprockets-es6"

gem "factory_bot_rails"

gem "decidim-bulletin_board", path: "../ruby-client"

gem "voting_schemes-dummy", path: "../../voting_schemes/dummy/ruby-adapter"
gem "voting_schemes-electionguard", path: "../../voting_schemes/electionguard/ruby-adapter"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "cypress-on-rails", "~> 1.0"
  gem "graphlient", "~> 0.5.0"
  gem "net-imap", "~> 0.2.3"
  gem "net-pop", "~> 0.1.1"
  gem "net-smtp", "~> 0.3.1"
  gem "pry-rails"
  gem "rspec-rails", "~> 4.1"
  gem "rubocop", "~> 1.57.0"
  gem "rubocop-faker", "~> 1.1"
  gem "rubocop-graphql", "~> 0.14.4"
  gem "rubocop-rails", "~> 2.22"
  gem "rubocop-rspec", "~> 2.20"
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "listen", "~> 3.2"
  gem "web-console", ">= 3.3.0"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  gem "database_cleaner-active_record"

  gem "rspec-graphql_matchers"
  gem "wisper-rspec"

  gem "simplecov", require: false
  gem "simplecov-cobertura"
end

group :production do
  gem "sidekiq", "~> 6.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
