package:
  name: libgmp
  version: 6.2.1

source:
  sha256: fd4829912cddd12f84181c3451cc752be224643e87fac497b69edddadc49b4f2
  url: https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz

build:
  library: true
  script: |
     CFLAGS="-fPIC" gmp_asm_syntax_testing="no" emconfigure ./configure --prefix=$PWD --disable-assembly --disable-assert --disable-shared; \
     emmake make install -j ${PYODIDE_JOBS:-3}
