default: &default
  iat_expiration_minutes: 60
  create_election:
    hours_before: 2
  cors_origin_allowed: "localhost:3000"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  cors_origin_allowed: <%= ENV["CORS_ORIGIN_ALLOWED"] %>
