name: "[CI] Lint"
on: push
# on:
#   push:
#     paths:
#       - ./decidim-bulletin-board-app

env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 2.6.6

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./decidim-bulletin-board-app
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Ruby deps
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd decidim-bulletin-board-app && bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Install Rubocop
        run: gem install rubocop
      - run: bundle exec rubocop -P
        name: Lint Ruby files
  rspec-test:
    name: RSpec tests
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install Ruby deps
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake
