name: "Pull request best practises"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check_title:
    name: Check title
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          disallowed_prefixes: "feat:,chore:,fix:,build:,ci:,refactor:,docs:"
          prefix_case_sensitive: true
