name: "Pull request best practises"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check_title:
    name: Check title
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.2
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: deepakputhraya/action-pr-title@master
        with:
          disallowed_prefixes: "feat:,chore:,fix:,build:,ci:,refactor:,docs:"
          prefix_case_sensitive: true
