name: "[CI] Ruby Client"
on:
  pull_request:
    paths:
      - ".github/workflows/ruby-workflow.yml"
      - "decidim-bulletin_board-ruby/**"
  push:
    branches:
      - develop
      - main

env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 2.6.6

defaults:
  run:
    working-directory: ./decidim-bulletin_board-ruby

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Recover dependency cache
        uses: actions/cache@v1
        with:
          path: ./decidim-bulletin_board-ruby/vendor/bundle
          key: ${{ runner.OS }}-decidim-bulletin_board-ruby-deps-${{ hashFiles('decidim-bulletin_board-ruby/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-decidim-bulletin_board-ruby-deps-${{ env.cache-name }}-
            ${{ runner.OS }}-decidim-bulletin_board-ruby-deps-
            ${{ runner.OS }}-decidim-bulletin_board-ruby-
      - name: Install Ruby deps
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd decidim-bulletin_board-ruby && bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Install Rubocop
        run: gem install rubocop
      - run: bundle exec rubocop -P
        name: Lint Ruby files
  rspec-test:
    name: RSpec tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Recover dependency cache
        uses: actions/cache@v1
        with:
          path: ./decidim-bulletin_board-ruby/vendor/bundle
          key: ${{ runner.OS }}-decidim-bulletin_board-ruby-deps-${{ hashFiles('decidim-bulletin_board-ruby/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-decidim-bulletin_board-ruby-deps-${{ env.cache-name }}-
            ${{ runner.OS }}-decidim-bulletin_board-ruby-deps-
            ${{ runner.OS }}-decidim-bulletin_board-ruby-
      - name: Install Ruby deps
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd decidim-bulletin_board-ruby && bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Run tests
        run: bundler exec rake
