name: "[CI] Electionguard Voting Scheme JS Adapter"
on:
  pull_request:
    paths:
      - ".github/workflows/voting-scheme-electionguard-js-adapter-workflow.yml"
      - "voting_schemes/electionguard/js-adapter/**"
  push:
    branches:
      - develop
      - main

env:
  CI: "true"
  SIMPLECOV: "true"
  RUBY_VERSION: 3.1.1
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
  NODE_VERSION: "15"

defaults:
  run:
    working-directory: ./voting_schemes/electionguard/js-adapter

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.2
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Recover packages cache
        uses: actions/cache@v1
        with:
          path: ./voting_schemes/electionguard/js-adapter/node_modules
          key: ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-deps-${{ hashFiles('voting_schemes/electionguard/js-adapter/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-deps-${{ env.cache-name }}-
            ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-deps-
            ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-
      - name: Install Javascript deps
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd voting_schemes/electionguard/js-adapter && npm ci
      - run: npm run lint
        name: Lint JS files
      - run: npm run format
        name: Format JS files
  unit-tests:
    name: Unit tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.2
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Recover packages cache
        uses: actions/cache@v1
        with:
          path: ./voting_schemes/electionguard/js-adapter/node_modules
          key: ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-deps-${{ hashFiles('voting_schemes/electionguard/js-adapter/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-deps-${{ env.cache-name }}-
            ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-deps-
            ${{ runner.OS }}-voting_schemes/electionguard/js-adapter-js-
      - name: Install Javascript deps
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd voting_schemes/electionguard/js-adapter && npm ci
      - name: Run Jest tests
        run: npm run test
